@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImlhdCI6MTcyMjk1NDU3NywiZXhwIjoxNzI1NTQ2NTc3fQ.qeo4T2_TS7h9YRidLY6wWtr7C2gryCESHNc0l1EoCu0
@baseUrl = http://localhost:5000

######################################################################################
##################################### users #####################################
######################################################################################

### User login
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "dni": 28470359,
  "password": "pass"
}


### user registry (admin auth required)
POST {{baseUrl}}/api/users/
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "nombre_1":"",
   "nombre_2":"",
   "apellido_1":"gonzalez",
   "apellido_2":"",
   "dni":"1133355332",
   "foto":"",
   "email":"noesvacio7@gmail.com",
   "password":"",
   "telefono":"",
   "estado":"",
   "direcciones_id": 1  
}

### user update 
PUT {{baseUrl}}/api/users/91
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "estado":1
}

### getAllUsers
GET {{baseUrl}}/api/users
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### getById
GET {{baseUrl}}/api/users/97
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### deleteById

DELETE {{baseUrl}}/api/users/90
Content-Type: application/json
Authorization: Bearer {{adminToken}}

######################################################################################
##################################### DATALOGGERS ####################################
######################################################################################

### Dataloggers getById
GET {{baseUrl}}/api/dataloggers/3
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### Dataloggers getAll
GET {{baseUrl}}/api/dataloggers
Content-Type: application/json
Authorization: Bearer {{adminToken}}

###  Datalogger register
POST {{baseUrl}}/api/dataloggers/
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "direccion_mac":"2F:88:E7:FF:87:sa",
   "nombre":"DATALOgger API",
   "descripcion":"Es un datalogger falso, agregado para la prueba de la API",   
   "foto":"dataloggerFalso.jpg",
   "nombre_tabla":"datalogger_falso",
   "ubicacion_id": 34   
}

### Datalogger update
PUT {{baseUrl}}/api/dataloggers/23
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "nombre": "Datalogger API TEST"
}

### datalogger delete
DELETE {{baseUrl}}/api/dataloggers/26
Content-Type: application/json
Authorization: Bearer {{adminToken}}