@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImlhdCI6MTcyMjk1NDU3NywiZXhwIjoxNzI1NTQ2NTc3fQ.qeo4T2_TS7h9YRidLY6wWtr7C2gryCESHNc0l1EoCu0
@baseUrl = http://localhost:5000

######################################################################################
##################################### users #####################################
######################################################################################

### User login
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "dni": 28470359,
  "password": "pass"
}


### user registry (admin auth required)
POST {{baseUrl}}/api/users/
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "nombre_1":"",
   "nombre_2":"",
   "apellido_1":"gonzalez",
   "apellido_2":"",
   "dni":"1133355332",
   "foto":"",
   "email":"noesvacio7@gmail.com",
   "password":"",
   "telefono":"",
   "estado":"",
   "direcciones_id": 1  
}

### user update 
PUT {{baseUrl}}/api/users/91
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "estado":1
}

### getAllUsers
GET {{baseUrl}}/api/users
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### getById
GET {{baseUrl}}/api/users/97
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### deleteById

DELETE {{baseUrl}}/api/users/90
Content-Type: application/json
Authorization: Bearer {{adminToken}}

######################################################################################
##################################### DATALOGGERS ####################################
######################################################################################

### Dataloggers getById
GET {{baseUrl}}/api/dataloggers/3
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### Dataloggers getAll
GET {{baseUrl}}/api/dataloggers
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### Dataloggers getAll by location
GET {{baseUrl}}/api/dataloggers/bylocation/36
Content-Type: application/json
Authorization: Bearer {{adminToken}}

###  Datalogger register
POST {{baseUrl}}/api/dataloggers/
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "direccion_mac":"2F:88:E7:FF:87:sa",
   "nombre":"DATALOgger API",
   "descripcion":"Es un datalogger falso, agregado para la prueba de la API",   
   "foto":"dataloggerFalso.jpg",
   "nombre_tabla":"datalogger_falso",
   "ubicacion_id": 34   
}

### Datalogger update
PUT {{baseUrl}}/api/dataloggers/23
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "nombre": "Datalogger API TEST"
}

### datalogger delete
DELETE {{baseUrl}}/api/dataloggers/26
Content-Type: application/json
Authorization: Bearer {{adminToken}}

######################################################################################
##################################### Locations ####################################
######################################################################################

### Locations getById
GET {{baseUrl}}/api/locations/34
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### Locations getAll
GET {{baseUrl}}/api/locations
Content-Type: application/json
Authorization: Bearer {{adminToken}}

###  Locations register
POST {{baseUrl}}/api/locations
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
   "nombre":"ubicacion API test",
   "descripcion":"Es un datalogger falso, agregado para la prueba de la API",   
   "foto":"dataloggerFalso.jpg",
   "telefono":"48416987",
   "email": "correo@gmail.com",
   "direcciones_id": 66   
}

### location update
PUT {{baseUrl}}/api/locations/432
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "nombre": "ubicacion API TEST 2"
}

### location delete
DELETE {{baseUrl}}/api/locations/43
Content-Type: application/json
Authorization: Bearer {{adminToken}}


######################################################################################
##################################### addresses ####################################
######################################################################################

### addresses getById
GET {{baseUrl}}/api/addresses/34
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### addresses getAll
GET {{baseUrl}}/api/addresses
Content-Type: application/json
Authorization: Bearer {{adminToken}}

###  addresses register
POST {{baseUrl}}/api/addresses
Content-Type: application/json
Authorization: Bearer {{adminToken}}

#calle, numero, localidad, partido, provincia, codigo_postal, latitud, longitud
{
   "calle":"Av. Siempre Viva",
   "numero": "155",   
   "localidad":"1212",
   "partido":"48416987",
   "provincia": "02",
   "codigo_postal": "66" ,
   "latitud" : "-31.5375",
   "longitud": "-68.5364"
}

### location update
PUT {{baseUrl}}/api/addresses/70
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "numero": "555"
}

### location delete
DELETE {{baseUrl}}/api/addresses/70
Content-Type: application/json
Authorization: Bearer {{adminToken}}

######################################################################################
##################################### channels ####################################
######################################################################################

### channels getById
GET {{baseUrl}}/api/channels/12
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### channels getAll
GET {{baseUrl}}/api/channels
Content-Type: application/json
Authorization: Bearer {{adminToken}}

###  channels register
POST {{baseUrl}}/api/channels
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
   "datalogger_id":"3",
   "nombre": "canal API test",   
   "descripcion":"Canal falso para probar la api de canales",
   "nombre_columna":"d2",
   "tiempo_a_promediar": "1 HOUR",
   "foto": "canales.jpg" ,
   "multiplicador" : "1"
}

### location update
PUT {{baseUrl}}/api/channels/26
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "nombre": "otro canal de prueba de la api"
}

### location delete
DELETE {{baseUrl}}/api/channels/27
Content-Type: application/json
Authorization: Bearer {{adminToken}}