POST https://whitesmoke-mule-983572.hostingersite.com/cocina/datos_esp.php
Content-Type: application/x-www-form-urlencoded

identificador=1
&tiempo_total=100
&d1_estado=1
&d1_cantidad=1
&d1_tiempo=10
&d2_estado=0
&d2_cantidad=0
&d2_tiempo=0
&d3_estado=0
&d3_cantidad=0
&d3_tiempo=0
&d4_estado=0
&d4_cantidad=0
&d4_tiempo=0
&d5_estado=0
&d5_cantidad=0
&d5_tiempo=0
&d6_estado=0
&d6_cantidad=0
&d6_tiempo=0
&d7_estado=0
&d7_cantidad=0
&d7_tiempo=0
&d8_estado=0
&d8_cantidad=0
&d8_tiempo=0
&a1_inst=1.1
&a1_min=1.0
&a1_max=1.2
&a1_estado=1
&a1_cantidad=1
&a1_tiempo=10
&a2_inst=0
&a2_min=0
&a2_max=0
&a2_estado=0
&a2_cantidad=0
&a2_tiempo=0
&a3_inst=0
&a3_min=0
&a3_max=0
&a3_estado=0
&a3_cantidad=0
&a3_tiempo=0
&a4_inst=0
&a4_min=0
&a4_max=0
&a4_estado=0
&a4_cantidad=0
&a4_tiempo=0
&a5_inst=0
&a5_min=0
&a5_max=0
&a5_estado=0
&a5_cantidad=0
&a5_tiempo=0
&servicio=1
&energia=1
&texto=test_from_http_file
